// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Image_API.Models
{
    public partial class Image
    {
        public long ID { get; set; }
        public string imagepath { get; set; }
        public string insertedOn { get; set; }
    }
}